### ISSUE TITLE
Add support for "doggy push ID ID ID"

### ISSUE THREAD

**Issue by marc-barry** [Shopify/doggy#19]
The [README](https://github.com/bai/doggy/blob/505b7a188320766972ea2cc08648100d8ed8a003/README.md) states under `Usage` the following:
```
# Upload selected items to DataDog
$ doggy push ID ID ID
```
But that functionality isn't actually supported. This is issue is for adding support for this functionality.

**Comment by marc-barry** [comment]
@ElvinEfendi I think this was added in a recent pull request. Am I correct?

**Comment by ElvinEfendi** [comment]
This has been fixed at https://github.com/Shopify/doggy/pull/22
