### ISSUE TITLE
Not setup with shipit

### ISSUE THREAD

**Issue by jules2689** [Shopify/doggy#50]
This gem is not currently owned by admins@shopify.com, nor can we push to it using Shipit deploys.

cc @bai @andremedeiros (current owners)

Can you make admins@shopify.com an owner please?

**Comment by andremedeiros** [comment]
```
~ > gem owner doggy
Owners for gem: doggy
- elvin.efendiyev@gmail.com
- v@gor.io
~ > gem owner doggy --add admins@shopify.com
Adding admins@shopify.com: You do not have permission to manage this gem.
```

Sorry. Has to be @bai or @ElvinEfendi

**Comment by jules2689** [comment]
Aha, awkward... you're an author though
![image](https://user-images.githubusercontent.com/3074765/35640151-62101f62-068a-11e8-944b-ae239323985a.png)

**Comment by andremedeiros** [comment]
Yeah, I can see how you thought I could help you here 😉

**Comment by ElvinEfendi** [comment]
```
> doggy (master)$ gem owner doggy -a admins@shopify.com
Owner added successfully.
Owners for gem: doggy
- admins@shopify.com
- elvin.efendiyev@gmail.com
- v@gor.io
```

**Comment by sbfaulkner** [comment]
@jules2689 are you unblocked on this now?

**Comment by jules2689** [comment]
looks like it
