### ISSUE TITLE
Rugged dependecny: Needed to be updated to 0.26.0

### ISSUE THREAD

**Issue by imriss** [Shopify/doggy#51]
Hi,

The `rugged` version is needed to be updated to "`0.26.0`". Currently, it is listed as "`0.23.2`" in the dependencies (`doggy.gemspec`), and there is an error while compiling:
```
error: dereferencing pointer to incomplete type ‘BIO {aka struct bio_st}’
```
The error also appears when `Rugged` `0.23.2` is directly installed (not as a dependency of `doggy`). However, there is no error when `rugged` `0.26.0` is directly installed.

Thanks.

**Comment by philCryoport** [comment]
Rugged 0.23.x appears to have a conflict with libopenssl 1.1.0

Rugged has been updated to an even later version 0.26 and later are compatible.  Please oh please update.

**Comment by bai** [comment]
Thanks, fixed this one.
